<?php
$GLOBALS['auth_lang_array']= array( 'cn'=>
array(
	'safety.auth'=>'安全认证',
	'auth.input.username'=>'用户名',
	'auth.input.password'=>'密码',
	'auth.old.password'=>'旧密码',
	'auth.new.password'=>'新密码',
	'auth.confirm.newpsd'=>'确认新密码',
	'auth.btn.submit'=>'登&nbsp;&nbsp;录',
	'auth.btn.submit.name'=>'登录名',
	'auth.btn.submit.ip'=>'登录IP',
	'auth.btn.submit.time'=>'登录时间',
	'auth.online.time'=>'在线时长',
	'auth.logout'=>'注销',
	'auth.changepsd'=>'修改密码',
	'auth.hours'=>'时',
	'auth.minutes'=>'分',
	'auth.seconds'=>'秒',
	'auth.cant.username.empty'=>'用户名不能为空',
	'auth.cant.password.empty'=>'密码不能为空',
	'auth.length.out'=>'用户名长度超出',
	'auth.length.range'=>'密码长度范围为6-31',
	'auth.username.psd.error'=>'用户名或密码错误',
	'auth.keepalive_Prompt'=>'建议上网期间保持此页面打开',
	'auth.enter.valid.character'=>'请输入合法字符,不能输入空格',
	'auth_error.usernull'=>'用户名不能为空',
	'auth_error.oldpwdnull'=>'旧密码不能为空',
	'auth_error.newpwdnull'=>'新密码不能为空',
	'auth_error.repwdnull'=>'重复密码不能为空',
	'auth_error.pwdnosame'=>'确认新密码与新密码的值不一致',
	'auth.enter.valid.allow.format'=>'请输入合法字符,例如:数字字母以及@._-()[]|',
	'auth_changepwd_sucess'=>'密码修改成功,&nbsp;&nbsp;',
	'auth_skip_login'=>'请返回登录页面',
	'auth.safety.certification'=>'安全认证',
	'auth.safety.notemptyusername'=>'用户名不能为空',
	'auth.safety.notintherangeusername'=>'用户名长度范围为1-31个字节',
	'auth.safety.notemptyoldpassword'=>'旧密码不能为空',
	'auth.safety.notemptynewpassword'=>'新密码不能为空',
	'auth.safety.notemptyconfirmpassword'=>'重复密码不能为空',
	'auth.safety.passwordnotinrange'=>'密码长度范围为6-31',
	'auth.safety.password'=>'密码长度范围为1-63个字符',
	'auth.safety.confirmpasswordnotsamewithnewpassword'=>'确认新密码与新密码的值不一致',
	'auth.safety.correctusername'=>'包含了不合法字符：%\"#$`*+,/:;<=>?\^\'{}!',
	'auth.safety.notemptypassword'=>'密码不能为空',
	'auth.safety.incorrectusernameorpass'=>'用户名或密码错误',
	'auth.safety.authtips'=>'建议上网期间保持此页面打开',
	'auth.safety.loginname'=>'登录名',
	'auth.safety.loginip'=>'登录IP',
	'auth.safety.logintiem'=>'登录时间',
	'auth.safety.onlinetime'=>'在线时长',
	'auth.safety.logout'=>'注销',
	'auth.safety.changepassword'=>'修改密码',
	'auth.safety.changepasswordsuccess'=>'密码修改成功',
	'auth.safety.returnloginpage'=>'请返回登录页面',
	'auth.safety.oldpassword'=>'旧密码',
	'auth.safety.newpassword'=>'新密码',
	'auth.safety.confirmpassword'=>'确认新密码',
	'auth.safety.confirmbtn'=>'确定',
	'auth.safety.canclebtn'=>'取消',
	'verify_num'=>'验证码',
	'check_num_error' => '验证码不正确',
	'check_num_empty' => '验证码不能为空',
	'sys_language_zh' => '中文',
	'sys_language_en' => '英文',
	'auth.input.lang' => '语言',
	'auth.config_error' => '模版不合法(不存在或者被拉黑)',
	'auth.not_config_dns' => '请查看DNS是否配置或配置错误',
	'auth.qrcode.span' => '二维码认证',
	'register.username.placeholder' => '请输入用户名称',
	'register.username.success.msg' => '认证成功',
	'register.timeout.msg' => '二维码超时',
	'auth.input.moblie'=>'手机号',
	'auth.input.getverifynum'=>'获取验证码',
	'auth.input.getverifynums'=>'秒后获取验证码',
	'auth.cant.moblie.empty'=>'手机号不能为空',
	'auth.cant.moblie.error'=>'手机号格式错误',
	'auth.cant.vldcode.empty'=>'验证码不能为空',
	'auth.cant.vldcode.error'=>'验证码格式错误',
	'auth.cant.vldcode.timeout'=>'验证码已过期',
	'auth.cant.vldcode.notmatch'=>'验证码与手机号不匹配',
	'auth.cant.vldcode.loginerr'=>'登录异常，请联系管理员',
	'auth.mix.chose.type'=>'选择认证方式',
	'auth.mix.local'=>'本地认证',
	'auth.mix.sms'=>'短信认证',
	'auth.mix.qrcode'=>'二维码认证',
	'auth.mix.free'=>'免认证',
	'auth.sms.aliconfig'=>'请配置阿里云短信平台相关内容',
	'auth.sms.product.fw'=>'防火墙'
),
'en' => array(
	'safety.auth'=>'Authentication',
	'auth.input.username'=>'Username',
	'auth.input.password'=>'Password',
	'auth.old.password'=>'Old Pwd',
	'auth.new.password'=>'New Pwd',
	'auth.confirm.newpsd'=>'Confirm Pwd',
	'auth.btn.submit'=>'Login',
	'auth.btn.submit.name'=>'Username',
	'auth.btn.submit.ip'=>'Login IP',
	'auth.btn.submit.time'=>'Logintime',
	'auth.online.time'=>'Online Time',
	'auth.logout'=>'Logout',
	'auth.changepsd'=>'Change Pwd',
	'auth.hours'=>'hours',
	'auth.minutes'=>'minutes',
	'auth.seconds'=>'seconds',
	'auth.cant.empty'=>'Input can not be empty',
	'auth.cant.username.empty'=>'Input User name can not be empty',
	'auth.cant.password.empty'=>'Input password name can not be empty',
	'auth.length.out'=>'Enter the length exceeds',
	'auth.length.range'=>'Password length range of 6-31',
	'auth.username.psd.error'=>'User name or password error',
	'auth.keepalive_Prompt'=>'It is recommended to keep this page open during Internet access',
	'auth.enter.valid.character'=>'Please enter a valid character, you can not enter a space',
	'auth_error.usernull'=>'User doesn\'t be null',
	'auth_error.oldpwdnull'=>'Old Password doesn\'t be null',
	'auth_error.newpwdnull'=>'New Password doesn\'t be null',
	'auth_error.repwdnull'=>'Repeat Password doesn\'t be null',
	'auth_error.pwdnosame'=>'Confirm Pwd and New Pwd  are inconsistent',
	'auth.enter.valid.allow.format'=>'Please enter valid characters,e.g.number,letters and @._-()[]|',
	'auth_changepwd_sucess'=>'Password modify success,&nbsp;&nbsp;',
	'auth_skip_login'=>'Please return to the login page',
	'auth.safety.certification'=>'Safety Certification',
	'auth.safety.notemptyusername'=>'username can not be empty',
	'auth.safety.notintherangeusername'=>'username length range is 1-31 byte',
	'auth.safety.notemptyoldpassword'=>'old password can not be empty',
	'auth.safety.notemptynewpassword'=>'new password can not be empty',
	'auth.safety.notemptyconfirmpassword'=>'confirm password can not be empty',
	'auth.safety.passwordnotinrange'=>'password length range is 6-31 character',
	'auth.safety.confirmpasswordnotsamewithnewpassword'=>'confirm new password not same with new password',
	'auth.safety.correctusername'=>'Contains invalid characters：%\"#$`*+,/:;<=>?\^\'{}!',
	'auth.safety.notemptypassword'=>'password can not be empty',
	'auth.safety.incorrectusernameorpass'=>'username or password error',
	'auth.safety.authtips'=>'It is recommended to keep this page open during Internet access',
	'auth.safety.password'=> 'Password length ranges from 1 to 63 characters',
	'auth.safety.loginname'=>'Login Name',
	'auth.safety.loginip'=>'Login IP',
	'auth.safety.logintiem'=>'Login Time',
	'auth.safety.onlinetime'=>'Online Time',
	'auth.safety.logout'=>'Logout',
	'auth.safety.changepassword'=>'Change Password',
	'auth.safety.changepasswordsuccess'=>'Change Password Successfully <br/>',
	'auth.safety.returnloginpage'=>'Please Return Login Page',
	'auth.safety.oldpassword'=>'Old Password',
	'auth.safety.newpassword'=>'New Password',
	'auth.safety.confirmpassword'=>'Confirm New Password',
	'auth.safety.confirmbtn'=>'Confirm',
	'auth.safety.canclebtn'=>'Cancel',
	'verify_num'=>'Verification Code',
	'check_num_error' => 'Validation code is incorrect',
	'check_num_empty' => 'The verifying code cannot be empty',
	'sys_language_zh' => 'Chinese',
	'sys_language_en' => 'English',
	'auth.input.lang' => 'Language',
	'auth.config_error' => 'The template is illegal (does not exist or is blacked)',
	'auth.not_config_dns' => 'Please check whether DNS is configured or configured incorrectly',
	'auth.qrcode.span' => 'QR code Auth',
	'register.username.placeholder' => 'Please enter user name',
	'register.username.success.msg' => 'Authentication is successful',
	'register.timeout.msg' => 'QRcode timeout',
	'auth.input.moblie'=>'Mobile:',
	'auth.input.getverifynum'=>'Get Code',
	'auth.input.getverifynums'=>'s later to get code',
	'auth.cant.moblie.empty'=>'Phone number cannot be empty',
	'auth.cant.moblie.error'=>'Malformed phone number',
	'auth.cant.vldcode.empty'=>'verification code must be filled',
	'auth.cant.vldcode.error'=>'Verification code format error',
	'auth.cant.vldcode.timeout'=>'Verification code timeout',
	'auth.cant.vldcode.notmatch'=>'Verification and Phone number are not match',
	'auth.cant.vldcode.loginerr'=>'Logon abnormal, please contact administrator',
	'auth.mix.chose.type'=>'Chose Authentication Type',
	'auth.mix.local'=>'Local Authentication',
	'auth.mix.sms'=>'SMS Authentication',
	'auth.mix.qrcode'=>'QRcode Authentication',
	'auth.mix.free'=>'Free Authentication',
	'auth.sms.aliconfig'=>'Please configure the relevant content of Aliyun SMS platform',
	'auth.sms.product.fw'=>'Firewall'
	)
);
function getCommonResource($key){
	$language = get_sys_language();
	return $GLOBALS['auth_lang_array'][$language][$key];
}
function get_sys_language(){
	$fp = fopen('/tmp/webui/lang.conf', 'r');
	$reg_msg = fread( $fp, filesize('/tmp/webui/lang.conf'));
	fclose($fp);
	if(strstr( $reg_msg, "1" ))
		return 'en';
	else
		return 'cn';
}
?>
