<?php
require_once '../common/cfgeng.inc';
require_once '../common/func.inc';
$GLOBALS['sslvpn_lang_array']= array( 'cn'=>
array(
	'sslvpn.input.username'=>'用户名:',
	'sslvpn.input.password'=>'密码:',
	'sslvpn_submit'=>'提&nbsp;交',
	'sslvpn.btn.submit'=>'登&nbsp;&nbsp;录',
	'sslvpn.btn.submit.name'=>'登录名',
	'sslvpn.btn.submit.ip'=>'登录IP',
	'sslvpn.btn.submit.time'=>'登录时间',
	'sslvpn.online.time'=>'在线时长',
	'sslvpn.hours'=>'时',
	'sslvpn.minutes'=>'分',
	'sslvpn.seconds'=>'秒',
	'sslvpn.cant.empty'=>'密码不能为空',
	'sslvpn.length.out'=>'长度超出',
	'sslvpn.length.range'=>'长度范围为6-63',
	'sslvpn.username.psd.error'=>'用户名或密码错误',
	'sslvpn.keepalive_Prompt'=>'请在上网期间保持此页面打开',
	'sslvpn.enter.valid.character'=>'请输入合法字符,不能输入空格',
	'sslvpn_error.usernull'=>'用户名不能为空',
	'sslvpn_error.oldpwdnull'=>'旧密码不能为空',
	'sslvpn_error.newpwdnull'=>'新密码不能为空',
	'sslvpn_error.repwdnull'=>'重复密码不能为空',
	'sslvpn_error.pwdnosame'=>'确认新密码与新密码的值不一致',
	'sslvpn_error.checkwrong'=>'验证失败',
	'sslvpn.enter.valid.allow.format'=>'请输入合法字符,例如:数字字母以及@._-()[]|',
	'sslvpn_changepwd_sucess'=>'密码修改成功',
	'sslvpn_skip_login'=>'请返回登录页面',
	'sslvpn_title'=>'VPN用户中心',
	'sslvpn_logout'=>'退出登录',
	'sslvpn_account'=>'账户管理',
	'sslvpn_changepsd'=>'密码修改',
	'sslvpn_old_password'=>'原密码',
	'sslvpn_new_password'=>'新密码',
	'sslvpn_confirm_newpsd'=>'确认新密码',
	'sslvpn_client_download'=>'客户端下载',
	'sslvpn_config_download'=>'配置文件下载',
	'sslvpn_help'=>'帮助中心',
	'sslvpn_help_doc'=>'SSLVPN帮助文档',
	'ipsec_help_doc'=>'IPSEC VPN帮助文档',
	'sslvpn_help_download'=>'帮助文档下载',
	'sslvpn_32_win'=>'Windows 32位客户端下载',
	'sslvpn_64_win'=>'Windows 64位客户端下载',
	'sslvpn_android'=>'安卓客户端下载',
	'sslvpn_ios'=>'iOS客户端下载',
	'sslvpn_no_down'=>'没有客户端可以下载',
	'sslvpn_32_winxp' => '32位Windows XP客户端下载',
	'sslvpn_64_winxp' => '64位Windows XP客户端下载',
	'sslvpn_32_vista' => 'Windows Vista及之后版本32位客户端下载',
	'sslvpn_64_vista' => 'Windows Vista及之后版本64位客户端下载',
	'sslvpn_tip_user_pass' => '(6-31 字符)',
	'sslvpn.length.pass'=>'密码长度范围为6-31',
	'sslvpn.error.msg' => '存在新的可用版本V，请前往VPN用户中心下载',
	'sslvpn.error.msgios' => '存在新的可用版本V，请前往APP Store下载',
),
'en' => array(
	'sslvpn.input.username'=>'Username:',
	'sslvpn.input.password'=>'Password:',
	'sslvpn_submit'=>'Sumbit',
	'sslvpn.btn.submit'=>'Login',
	'sslvpn.btn.submit.name'=>'Username',
	'sslvpn.btn.submit.ip'=>'Login IP',
	'sslvpn.btn.submit.time'=>'Logintime',
	'sslvpn.online.time'=>'Online Time',
	'sslvpn.hours'=>'hours',
	'sslvpn.minutes'=>'minutes',
	'sslvpn.seconds'=>'seconds',
	'sslvpn.cant.empty'=>'Password can not be empty',
	'sslvpn.length.out'=>'Enter the length exceeds',
	'sslvpn.length.range'=>'Length range of 6-63',
	'sslvpn.username.psd.error'=>'User name or password error',
	'sslvpn.keepalive_Prompt'=>'Keep this page open during the Internet',
	'sslvpn.enter.valid.character'=>'Please enter a valid character, you can not enter a space',
	'sslvpn_error.usernull'=>'User doesn\'t be null',
	'sslvpn_error.oldpwdnull'=>'Old Password doesn\'t be null',
	'sslvpn_error.newpwdnull'=>'New Password doesn\'t be null',
	'sslvpn_error.repwdnull'=>'Repeat Password doesn\'t be null',
	'sslvpn_error.pwdnosame'=>'Confirm Pwd and New Pwd  are inconsistent',
	'sslvpn_error.checkwrong'=>'Verification Failed',
	'sslvpn.enter.valid.allow.format'=>'Please enter valid characters,e.g.number,letters and @._-()[]|',
	'sslvpn_changepwd_sucess'=>'Password modify success',
	'sslvpn_skip_login'=>'Please return to the login page',
	'sslvpn_title'=>'VPN User Center',
	'sslvpn_logout'=>'Logout',
	'sslvpn_account'=>'Account',
	'sslvpn_changepsd'=>'Change Password',
	'sslvpn_old_password'=>'Old password',
	'sslvpn_new_password'=>'New password',
	'sslvpn_confirm_newpsd'=>'Confirm new passowrd',
	'sslvpn_client_download'=>'Client Download',
	'sslvpn_config_download'=>'Configuration Download',
	'sslvpn_help'=>'Help',
	'sslvpn_help_doc'=>'SSLVPN Help document',
	'ipsec_help_doc'=>'IPSEC VPN Help document',
	'sslvpn_help_download'=>'Help document Download',
	'sslvpn_32_win'=>'Windows Client（32bit）',
	'sslvpn_64_win'=>'Windows Client（64bit）',
	'sslvpn_android'=>'Android Client',
	'sslvpn_ios'=>'iOS Client',
	'sslvpn_no_down'=>'There is No client can be Download',
	'sslvpn_tip_user_pass' => '(6-31 character)',
	'sslvpn.length.pass'=>'Password length range of 6-31',
	'sslvpn.error.msg' => 'A new version V，available, Please download it',
	'sslvpn.error.msgios' => 'A new version V，available, Please go to APP Store for downloading it',
));
function getCommonResource($key){
	$language = get_sapl_language();
	return $GLOBALS['sslvpn_lang_array'][$language][$key];
}
function get_sapl_language(){
	//$fp = fopen('/usr/local/wwwroot/ui/lang.conf', 'r');
	$fp = fopen('/tmp/webui/lang.conf', 'r');
	//$reg_msg = fread( $fp, filesize('/usr/local/wwwroot/ui/lang.conf'));
	$reg_msg = fread( $fp, filesize('/tmp/webui/lang.conf'));
	fclose($fp);
	if(strstr( $reg_msg, "1" ))
		return 'en';
	else
		return 'cn';
}
?>
