<?php
require_once '../vendor/autoload.php';
require_once '../common/config.inc';
require_once '../common/cfgeng.inc';
require_once '../common/func.inc';
require_once '../common/common.inc';
require_once './libs/i18n.class.php';

@ini_set('session.use_cookies', 0);
@ini_set('session.use_only_cookies', 0);
@ini_set("session.auto_start", 1);
ini_set("error_reporting", 0);
ini_set("error_reporting", E_ERROR);
@ini_set("display_errors", "Off");
//debug调试方法，打开即可查看
/*@ini_set("display_errors", "On");
ini_set("error_reporting", E_ALL);
error_reporting(E_ALL);*/

$request_data = array();

function get_inputs()
{
	global $request_data;
	$content_type = $_SERVER['CONTENT_TYPE'];
	if (strstr($content_type, "application/json")) {
		$str = file_get_contents('php://input');
		$json = json_decode($str, true);
		if ($json) {
			return array_merge($json, get_gets());
		}
		return get_gets();
	}

	$method = $_SERVER['REQUEST_METHOD'];
	if ($method == 'PUT' || $method == 'DELETE') {
		parse_str(file_get_contents('php://input'), $data);
		$request_data  = array_merge($_POST, $data);
		$request_data = array_merge($request_data, get_gets());
	} else if ($method == 'POST') {
		$request_data  = $_POST;
		if(!isset($_POST['lang'])){
			$request_data = array_merge($request_data, get_gets());
		}
	} else if ($method == 'GET') {
		$request_data  = get_gets();
	}
	$filter_request_data = array();
	foreach ($request_data as $key => $value) {
		//修改数组为array时的处理
		if (!is_array($value)) {
			$filter_value = htmlspecialchars($value);
			$filter_request_data[$key] = $filter_value;
		} else {
			$filter_request_data[$key] = $value;
		}

	}

	return $filter_request_data;
	//return $request_data;
}

function get_gets()
{
	$ret = array();;
	$arr = $_GET;

	foreach ($arr as $key => $v) {
		if ($key != 'api_key') {
			$ret[$key] = htmlspecialchars($v);
		}
	}
	return $ret;
}

#locale
$i18n = new i18n();
$i18n->setFallbackLang('en');
$i18n->setFilePath('./resource/lang/{LANGUAGE}.yml');
$i18n->init();

function t($str) {
    $str = str_replace('.', '_', $str);
    return L($str);
}

ToroHook::add("404",  function() {
	$ret = array('code' => '-1000', 'str' => 'api is not found');
	echo json_encode($ret);
	exit(0);
});

Toro::serve(array(
	/*login*/
	"login" => "controller\login\LoginController",
	"logout" => "controller\login\LogoutController",
	"captcha" => "controller\login\CaptchaController",
	// "sso-key" => 'controller\login\SSOLoginController',
	"randomkey" => 'controller\login\CryptKeyController',
	"login-state" => "controller\login\LoginStateController",
	"sso" => "controller\login\SSOController",
	"ssologin" => "controller\login\SSOLoginController",
	"sso-auth" => "controller\login\SSOAuthController",
	"reset-pwd" => "controller\login\ResetPwdController",
	"admin-otp-check" => "controller\login\AdminOtpCheckController",
	"websev-test" => "controller\login\WebsevTestController",
	"sso-token"=> "controller\login\SSOTokenController",
    "sso-login"=> "controller\login\SSOAuthLoginController",
    "sso-reset-pwd"=> "controller\login\SSOResetPwdController",
    "sso-360" => "controller\login\SSOSingleAuthController",
	/*statistics*/
	"guide-page"=>"controller\statistics\GuidePageController",
	"dashboard" => "controller\statistics\DashboardController",
	"layoutlist" => "controller\statistics\LayoutlistController",
	"device-status" => "controller\statistics\DeviceStatusController",
	"device-pref" => "controller\statistics\DevicePrefController",
	"device-connect" => "controller\statistics\DeviceConnectController",
	"app-monitor" => "controller\statistics\AppMonitorController",
	"app-monitor-stat" => "controller\statistics\AppMonitorStatController",
	"online-user" => 'controller\statistics\OnlineUserMonitorController',
	"online-user-statistic" => 'controller\statistics\OnlineUserStatisticController',
    "interface-monitor" => 'controller\statistics\InterfaceMonitorController',
    "session-stat" => 'controller\statistics\SessionStatController',
    "session-scout" => 'controller\statistics\SessionScoutController',
	"flow-stat-policy"=>'controller\statistics\FlowStatPolicyController',
	"flow-stat-table"=>'controller\statistics\FlowStatTableController',
	"host-info"=>'controller\statistics\HostInfoController',
	"user-monitor-trend"=>'controller\statistics\UserMonitorTrendController',
	"user-monitor"=>'controller\statistics\UserMonitorController',
	"interface-info"=>'controller\statistics\InterfaceInfoController',
	"app-monitor-trend"=>'controller\statistics\AppMonitorTrendController',
	"web-host"=>'controller\statistics\WedStatHostController',
	"web-user"=>'controller\statistics\WedStatUserController',
	"web-category"=>'controller\statistics\WedStatCategoryController',
	"web-detail"=>'controller\statistics\WedStatDetailController',
	"web-list"=>'controller\statistics\WedStatListController',
	"web-tend"=>'controller\statistics\WedStatTendController',
	"ips-sip"=>'controller\statistics\IpsStatSipController',
	"ips-dip"=>'controller\statistics\IpsStatDipController',
	"ips-event"=>'controller\statistics\IpsStatEventController',
	"ips-map"=>'controller\statistics\IpsStatMapController',
	"ips-list"=>'controller\statistics\IpsStatListController',
	"av-sip"=>'controller\statistics\AvStatSipController',
	"av-dip"=>'controller\statistics\AvStatDipController',
	"av-event"=>'controller\statistics\AvStatEventController',
	"apt-result"=>'controller\statistics\AptStatResultController',
	"apt-type"=>'controller\statistics\AptStatTypeController',
	"apt-list"=>'controller\statistics\AptStatListController',
	"cpu-stat"=>'controller\statistics\CpuStatController',
	"memory-stat"=>'controller\statistics\MemoryStatController',
	"appname-monitor-trend"=>'controller\statistics\AppnameMonitorTrendController',
	"username-monitor"=>'controller\statistics\UserNameMonitorController',
	"username-monitor-trend"=>'controller\statistics\UserNameMonitorTrendController',
	"interface-vsys"=>'controller\statistics\InterfaceVsysController',
	"health-stat"=> 'controller\statistics\HealthStatController',
	"lte-tacci"=> 'controller\statistics\LteTacciController',
	"lte-rsrp"=> 'controller\statistics\LteRsrpController',
	"host-traffic"=> 'controller\statistics\HostTrafficController',
	"host-state"=> 'controller\statistics\HostStateController',
	"health-check-state" => 'controller\statistics\HealthCheckStateController',
	"host-flow" => 'controller\statistics\HostFlowController',
	"safety-sip" => 'controller\statistics\SafetySipController',
	"safety-map" => 'controller\statistics\SafetyMapController',
	"log_timeline" => 'controller\statistics\LogTimelineController',
	"assets-sec-state" => 'controller\statistics\AssetsSecStatController',
	"assets-sec-user" => 'controller\statistics\AssetsSecUserController',
	"assets-sec-enable" => 'controller\statistics\AssetsSecEnableController',
	"attack-user" => 'controller\statistics\AttackUserController',
	"attack-trend" =>'controller\statistics\AttackTrendController',
	"attack-trend-stat" =>'controller\statistics\AttackTrendStatController',
	"attack-trend-detail" =>'controller\statistics\AttackTrendDetailController',
	"threat-hotspot"=>'controller\statistics\ThreatHotspotController',
	"intelligence-statistic" => 'controller\statistics\IntelligenceStatisticController',
	"threat-intelligence-list" => 'controller\statistics\ThreatIntelligenceListController',
	"attack-list-stat" =>'controller\statistics\AttackListStatController',
	"attack-list-detail" =>'controller\statistics\AttackListDetailController',
	"healthcheck-link"=>'controller\statistics\HealthcheckLinkController',
	"src-app-audit"=>'controller\statistics\SrcAppAuditController',
	"dst-app-audit"=>'controller\statistics\DstAppAuditController',
	"name-app-audit"=>'controller\statistics\NameAppAuditController',
	"app-profile"=> 'controller\statistics\AppProfileController',
	/*policy*/
    "nat-pool" => "controller\policy\NatPoolController",
    "nat-pool-check" => "controller\policy\NatPoolCheckController",
	"defense" => "controller\policy\DefenseController",
	"nat" => "controller\policy\NatController",
	"snat" => "controller\policy\SNatController",
	"dnat" => "controller\policy\DNatController",
	"policy" => "controller\policy\PolicyController",
	"policy-analysis" => "controller\policy\PolicyAnalysisController",
	"mirror-policy" => "controller\policy\MirrorPolicyController",
	"mirror-policy-state" => 'controller\policy\MirrorPolicyStateController',
	"auth-policy" => "controller\policy\AuthPolicyController",
	"ips-rule" => "controller\policy\IpsRuleController",
	"ips-log" => "controller\policy\IpsLogController",
	"ips-set" => "controller\policy\IpsSetController",
	"ips-set-detail" => "controller\policy\IpsSetDetailController",
	"ips-sig-node" => "controller\policy\IpsSigNodeController",
	"ips-sig-query" => "controller\policy\IpsSigQueryController",
	"ips-cls-load" => "controller\policy\IpsClsLoadController",
	"ips-custom" => "controller\policy\IpsCustomController",
	"ips-custom-import" => "controller\policy\IpsCustomImportController",
	"idp-linkage" => "controller\policy\IpsLinkageController",
	"av-filetype" => "controller\policy\AvFileController",
	"av-engine" => "controller\policy\AvEngineController",
	"session-proto" => "controller\policy\SessionProtoController",
    "nbc-qos" => "controller\policy\NbcQosController",
    "nbc-tm" => "controller\policy\NbcTmController",
    "nbc-quota" => "controller\policy\NbcQuotaController",
    "nbc-quota-recored" => "controller\policy\NbcQuotaRecoredController",
    "nbc-qos-punish" => "controller\policy\NbcQosPunishController",
    "nbc-qos-pstate" => "controller\policy\NbcQosPstateController",
	"app-policy" => "controller\policy\AppPolicyController",
	"web-policy" => "controller\policy\WebPolicyController",
	"web-rule" => "controller\policy\WebRuleController",
	"app-audit" => "controller\policy\AppAuditController",
	"app-whitelist" => "controller\policy\AppWhitelistController",
	"app-whitelist-url" => "controller\policy\AppWhitelistUrlController",
	"nbc-tmview" => "controller\policy\NbcTmViewController",
	"nbc-exclude"=> "controller\policy\NbcExcludeController",
	"app-action"=> "controller\policy\AppActionController",
	"app-rule"=> "controller\policy\AppRuleController",
	"apt-config"=> "controller\policy\AptConfigController",
	"nat-port"=> "controller\policy\NatPortController",
	"av-sig"=> "controller\policy\AvSigController",
	"av-rule" => "controller\policy\AvRuleController",
	"av-whitelist" => "controller\policy\AvWhitelistController",
	"blacklist"=> 'controller\policy\BlacklistController',
	"blacklist-backup"=> 'controller\policy\BlacklistBackupController',
	"blacklist-domain"=> 'controller\policy\BlacklistDomainController',
	"blacklist-statistics"=> 'controller\policy\BlacklistStatisticsController',
	"dos"=> 'controller\policy\DosController',
	"ecd-item"=> 'controller\policy\EcdItemController',
	"reliable-config"=> 'controller\policy\ReliableConfigController',
	"intelligence-level"=> 'controller\policy\IntelligenceLevelController',
	"defense-source" => 'controller\policy\DefenseSourceController',
	"nat-trans" => 'controller\policy\NatTransController',
	"policy-state" => 'controller\policy\PolicyStateController',
	"app-https" => 'controller\policy\AppHttpsController',
	"dns-resolution" => 'controller\policy\DnsResolutionController',
	"dst-nat-config" => 'controller\policy\DstNatFastCfgController',
	"config" => 'controller\policy\ConfigController',
	"attack-detection" => 'controller\policy\AttackDetectionController',
	"port-scan-res" => 'controller\policy\PortScanResController',
	"port-scan" => 'controller\policy\PortScanController',
	"port-scan-syn" => 'controller\policy\PortScanSynController',
	"port-scan-import" => 'controller\policy\PortScanImportController',
	"dictionary" => 'controller\policy\DictionaryController',
	"dictionary-import" => 'controller\policy\DictionaryImportController',
	"weak-pwd-scan" => 'controller\policy\WeakPwdScanController',
	"weak-pwd-res" => 'controller\policy\WeakPwdResController',
	"weak-pwd-import" => 'controller\policy\WeakPwdImportController',
	"ics-setting" => 'controller\policy\IcsSettingController',
	"ics-device" => 'controller\policy\IcsDeviceController',
	"eth-vendor" => 'controller\policy\EthVendorController',
	"sms-user-auth" => 'controller\policy\SmsUserAuthController',
	"nat-rule-state" => "controller\policy\NatRuleStateController",
	"dns-tunnel" => "controller\policy\DnsTunnelController",
	"arp-anti-spoof" => "controller\policy\ArpAntiSpoofController",
	"arp-anti-flood" => "controller\policy\ArpAntiFloodController",
	"arp-ctrl-learn" => "controller\policy\ArpCtrlLearnController",
	"arp-exempt-mac" => "controller\policy\ArpExemptMacController",
	"intelligence-database" => "controller\policy\IntelligenceDatabaseController",
	"check-update" => "controller\policy\IntelligenceCheckUpdateController",
	"ioc-update" => "controller\policy\IntelligenceIocUpdateController",
	"ioc-lasttime" => "controller\policy\IntelligenceIocLasttimeController",
	"register" => "controller\policy\IntelligenceRegisterController",
	"check-online" => "controller\policy\IntelligenceCheckOnlineController",
	"coo-def-cloud" => "controller\policy\CooDefCloudController",
	"edr-center" => "controller\policy\EdrCenterController",
	"edr-install" => "controller\policy\EdrInstallController",
	"edr-policy" => "controller\policy\EdrPolicyController",
	"edr-user" => "controller\policy\EdrUserController",
	"edr-https" => "controller\policy\EdrHttpsController",
	"user-security" => "controller\policy\UserSecurityController",
	"user-security-lock" => "controller\policy\UserSecurityLockController",
	"resource-policy" => "controller\policy\ResourcePolicyController",
	"resource-policy-state" => "controller\policy\ResourcePolicyStateController",
	"resource-policy-statistics" => "controller\policy\ResourcePolicyStatisticsController",
	"tiagnet-ioclib" => "controller\policy\IntelligenceLookupController",
	"lb-policy" => "controller\policy\IbPolicyController",
	"lb-policy-except" => "controller\policy\IbPolicyExceptController",
	"persist" => "controller\policy\PersistController",
	"exconn-policy" => "controller\policy\ExconnPolicyController",
	"exconn-rule" => "controller\policy\ExconnRuleController",
	"exconn-policy-state" => "controller\policy\ExconnPolicyStateController",
	"exconn-study" => "controller\policy\ExconnStudyController",
	"exconn-study-addr" => "controller\policy\ExconnStudyAddrController",
	"integration-strategy-addr"=>'controller\policy\IntegrationsTrategyAddrController',
	"integration-strategy-service"=>'controller\policy\IntegrationsTrategyServiceController',
	"integration-strategy-users"=>'controller\policy\IntegrationsTrategyUsersController',
	"divert-policy" => 'controller\policy\DivertPolicyController',
	"ssl-offload" => 'controller\policy\SSLOffloadController',
	'wechat-cnf' => 'controller\policy\WechatCnfController',
	"web-access-log-merge" => 'controller\policy\WebAccessLogMergeController',
	/*object*/
	"address" => "controller\object\AddressController",
	"address-group" => "controller\object\AddressGroupController",
	"address-detail" => "controller\object\AddressDetailController",
	"address-object" => "controller\object\AddressObjectController",
	"address-group-object" => "controller\object\AddressGroupObjectController",
	"address-geo-object" => "controller\object\AddressGeoObjectController",
    "service" => "controller\object\ServiceController",
	"service-group" => "controller\object\ServiceGroupController",
	"service-predefined" => "controller\object\ServicePreController",
	"service-predefined-object" => "controller\object\ServicePreObjectController",
	"service-object" => "controller\object\ServiceObjectController",
	"service-group-object" => "controller\object\ServiceGroupObjectController",
	"user-group" => "controller\object\UserGroupController",
	"user-object" => "controller\object\UserObjectController",
	"user-group-object" => "controller\object\UserGroupObjectController",
	"user-show" => "controller\object\UserShowController",
	"user-tree" => "controller\object\UserTreeController",
	"auth-user" => "controller\object\UserController",
	"user-sync" => "controller\object\UserSyncController",
	"user-sync-opt" => "controller\object\UserSyncOptController",
	"snmp-sync" => "controller\object\SnmpSyncController",
	"snmp-sync-opt" => "controller\object\SnmpSyncOptController",
	"radius-server" => "controller\object\RadiusServerController",
	"ldap-server" => "controller\object\LdapServerController",
	"app" => "controller\object\AppController",
	"abs-time" => "controller\object\AbsTimeController",
	"cyc-time" => "controller\object\CycTimeController",
	"keyword" => "controller\object\KeywordController",
	"keyword-filter" => "controller\object\KeywordFilterController",
	"app-content"=> "controller\object\AppContentController",
	"app-category"=> "controller\object\AppCategoryController",
	"url-category"=> "controller\object\UrlCategoryController",
	"url-userdefined"=> "controller\object\UrlCustomController",
	"filetype"=> "controller\object\FiletypeController",
	"health-check"=> "controller\object\HealthcheckController",
	"health-check-group"=> "controller\object\HealthcheckGroupController",
	"local-auth"=> "controller\object\LocalAuthController",
	"isp"=> "controller\object\ISPController",
	"geo"=> "controller\object\GEOController",
	"geo-addr"=> "controller\object\GEOAddrController",
	"portal-server"=> "controller\object\PortalServerController",
	"app-group"=> "controller\object\AppGroupController",
	"ca-cert"=> 'controller\object\CaCertController',
	"auth-portal-escape" => 'controller\object\AuthPortalEscapeController',
	"userdefined-rule" => 'controller\object\UserdefinedRuleController',
	"userdefined-plcy" => 'controller\object\UserdefinedPlcyController',
	"web-whitelist"=> 'controller\object\WebWhitelistController',
	"crl-cert"=> 'controller\object\CrlCertController',
	"root-ca-cert"=> 'controller\object\RootCaCertController',
	"ca-cert-req"=> 'controller\object\CaCertRequestController',
	"root-ca-cert-exp"=> 'controller\object\RootCaCertExportController',
	"root-ca-cert-imp"=> 'controller\object\RootCaCertImportController',
	"root-ca-crl"=> 'controller\object\RootCaCrlController',
	"root-ca-crl-conf"=> 'controller\object\RootCaCrlConfController',
	"root-ca-crl-exp"=> 'controller\object\RootCaCrlExportController',
	"ca-cert-list"=> 'controller\object\CaCertListController',
	"user-cert-req"=> 'controller\object\UserCertRequestController',
	"user-cert-info"=> 'controller\object\UserCertInfoController',
	"user-cert-exp"=> 'controller\object\UserCertExportController',
	"user-cert-issue"=> 'controller\object\UserCertIssueController',
	"user-cert-revoke"=> 'controller\object\UserCertRevokeController',
	"address-backup"=> 'controller\object\AddressBackupController',
	"dhcp-backup"=> 'controller\object\DhcpBackupController',
	"arp-backup"=> 'controller\object\ArpBackupController',
	"url-backup"=> 'controller\object\UrlBackupController',
	"user-remote"=> 'controller\object\UserRemoteController',
	"ssl-local-cert" => 'controller\object\SSLLocalCertController',
	"ssl-virtul-service" => 'controller\object\SSLVirtulServiceController',
	"ssl-virtul-address" => 'controller\object\SSLVirtulAddressController',
	"ssl-service-pool" => 'controller\object\SSLServicePoolController',
	"ssl-server-node" => 'controller\object\SSLServerNodeController',
	"ssl-server" => 'controller\object\SSLServerController',
	"ssl-client" => 'controller\object\SSLClientController',
	"ssl-pool-member" => 'controller\object\SSLPoolMemberController',
	"root-ca-trans" => 'controller\object\RootCaTransController',
	"root-ca-trust" => 'controller\object\RootCaTrustController',
	"assets-mgmt" => 'controller\object\AssetsMgmtController',
	"assets-cfg" => 'controller\object\AssetsCfgController',
	"assets-import" => 'controller\object\AssetsImportController',
	"assets-service" => 'controller\object\AssetsServController',
	"dynamic-pwd" => 'controller\object\DynamicPwdController',
	"sms-auth" => 'controller\object\SMSAuthController',
	"auth-adsso-setting" => 'controller\object\AuthAdssoSettingController',
	"download-single-program" => "controller\object\DownloadSingleSignProgramController",
	"auth-sms-profile" => 'controller\object\AuthSmsProfileController',
	"auth-qrcode-profile" => 'controller\object\AuthQrcodeProfileController',
	"domain-addr-dns" =>'controller\object\DomianAddrDnsController',
	"resource" =>'controller\object\ResourceController',
	"resource-group" =>'controller\object\ResourceGroupController',
	"resource-backup" =>'controller\object\ResourceBackupController',
	"resource-object" =>'controller\object\ResourceObjectController',
	"resource-group-object" =>'controller\object\ResourceGroupObjectController',
	"auth-free-profile"=>'controller\object\AuthFreeProfileController',
	"lb-interface-pool"=>'controller\object\LbInterfacePoolController',
	"geo-file" => "controller\object\GeoFileController",
//	"get-city-name"=>'controller\object\GetCityNameByIPController',
	"app-profile-filter" => "controller\object\AppProfileFilterController",
	"wechat-whitelist" => "controller\object\WechatWhiteListController",
	/*system*/
	"vrf" => "controller\system\VRFController",
	"admin" => "controller\system\AdminUserController",
	"cloud-agent" => "controller\system\CloudAgentController",
	"cloud-agent-stat" => "controller\system\CloudAgentStatController",
	"cloud-agent-flow" => "controller\system\CloudAgentFlowController",
	"cloud-agent-frp" => "controller\system\CloudAgentFrpController",
	"sys-conf" => "controller\system\SysSettingController",
	"host-name" => "controller\system\HostNameController",
	"dns" => "controller\system\DNSController",
	"time" => "controller\system\TimeConfigController",
	"ha-config" => "controller\system\HaConfigController",
	"ha-configsync" => "controller\system\HaConfigSynController",
    "ha-sessionsync" => "controller\system\HaSessionSynController",
    "syslog-server" => "controller\system\SyslogServerController",
    "snmp-config" => "controller\system\SNMPConfigController",
    "snmp-user" => "controller\system\SNMPUserController",
	"utmbcp-s2b" => "controller\system\UtmbcpS2bController",
	"utmbcp-b2s" => "controller\system\UtmbcpB2sController",
	"sysconf-file" => "controller\system\SysCfgFileController",
	"diagnostic-file" => "controller\system\DiagnosticFileController",
	"license"=> "controller\system\LicenseController",
	"online-license"=> "controller\system\OnlineLicenseController",
	"authorize-license"=> "controller\system\AuthorizeLicenseController",
	"authorize-active"=> "controller\system\AuthorizeActiveController",
	"sysconfig"=> "controller\system\SysConfigController",
	"flow-log"=> "controller\system\FlowLogController",
	"update-log"=> "controller\system\UpdateLogController",
	"ha-vlan"=> "controller\system\HaVlanController",
	"ha-healthcheck"=> "controller\system\HaHealthController",
	"ha-status"=> "controller\system\HaStatusController",
	"ha-control-all"=> "controller\system\HaControlAllController",
	"email-warning"=> "controller\system\EmailWarnController",
	"feedback"=> "controller\system\FeedbackController",
	"sys-resource"=> "controller\system\SysResourceController",
	"dns-detect" => 'controller\system\DNSDetectController',
 	"auto-update" => 'controller\system\AutoUpdateController',
 	"manual-update" => 'controller\system\ManualUpdateController',
 	"syslog-filter" => 'controller\system\SyslogFilterController',
	"syslog-threshold" => 'controller\system\SyslogThresholdController',
	"admin-online"=> 'controller\system\AdminOnlineController',
	"block-user"=> 'controller\system\BlockUserController',
	"ha-trunk"=> 'controller\system\HaTrunkController',
	"sys-vrrp"=> 'controller\system\SystemVrrpController',
	"ha_ifsync"=> 'controller\system\HaIfSyncController',
	"debug"=> 'controller\system\SysDebugController',
	"exception-message"=> 'controller\system\SysCoreController',
	"capture"=> 'controller\system\CaptureController',
	"capture-file"=>'controller\system\CaptureFileController',
	"ips-capture"=> 'controller\system\IpsCaptureController',
	"vrf"=>'controller\system\VRFController',
	"oem-feature"=>'controller\system\OemFeatureController',
	"disk-type"=>'controller\system\DiskTypeController',
	"unused-interface"=>'controller\system\UnusedInfController',
	"ha-inf-monitor"=>'controller\system\HaInfMonitorController',
	"ha-trunk-monitor"=>'controller\system\HaTrunkMonitorController',
	"ha-healthcheck-monitor"=>'controller\system\HaHealthcheckMonitorController',
	"interface-failsave"=>'controller\system\InterfaceFailsaveController',
	"phone-warning"=>'controller\system\PhoneWarnController',
	"reboot"=>'controller\system\SysRebootController',
	"sys-token"=>'controller\system\SysTokenController',
	"report-config"=>'controller\system\ReportCfgController',
	"auto-report"=> 'controller\system\ExportReportController',
	'report-day' => 'controller\system\ReportDayController',
	'report-week' => 'controller\system\ReportWeekController',
	'report-month' => 'controller\system\ReportMonthController',
	'report-cache' => 'controller\system\ReportCacheController',
	'download-report'=> 'controller\system\ReportDownloadController',
	'view-report'=> 'controller\system\ReportViewController',
	'three-power' => 'controller\system\ThreePowerController',
	'vsys' => 'controller\system\VsysController',
	'vsys-spec' => 'controller\system\VsysSpecController',
	'vsys-rule' => 'controller\system\VsysRuleController',
	'update-detect' => 'controller\system\UpdateDetectController',
	'oem-info' => 'controller\system\OemInfoController',
	"ping"=> 'controller\system\PingController',
	"trace"=> 'controller\system\TraceController',
	"delay-monitor"=> 'controller\system\DelayMonitorController',
	"admin-mode" => 'controller\system\AdminModeController',
	"admin-subauth-cfg" => "controller\system\AdminSubauthCfgController",
	"admin-key-manage" => "controller\system\AdminKeyManageController",
	"ips-warn-rule" => "controller\system\IpsWarnRuleController",
	"sysconf-config-export" => "controller\system\SysConfigExportController",
	"backup-version" => "controller\system\BackupVersionController",
	"cloud-cfg-save" => 'controller\system\CloudCfgSaveController',
	"frpc-hosts-cfg" => 'controller\system\FrpcHostsCfgController',
	"report-smtp" => 'controller\system\ReportSMTPController',
	"report-disk" => 'controller\system\ReportDiskController',
	"report-ftp" => 'controller\system\ReportFTPController',
	"drop-flow" => 'controller\system\DropFlowController',
	"drop-log" => 'controller\system\DropLogController',
	"syslog-docking" => 'controller\system\SyslogDockingController',
	"update-firmware" => 'controller\system\UpdateFirmareController',
	/*安恒对接接口*/
	"mssp/getRoles" => "controller\system\UserGetController",
	"mssp/setUserRoles" => "controller\system\UserSetController",
	"mssp/deleteUser" => "controller\system\UserDelController",
	"mssp/logout" => "controller\system\AnHengLogoutController",
	"mssp/modifyHost" => "controller\system\HostEditController",
	"mssp/modifyCasConfig" => "controller\system\CASEditController",
    /*syslog*/
    "email-cnt"=> 'controller\syslog\EmailCntController',
	"sys-log" => "controller\syslog\LogSysController",
	"audit-log" => "controller\syslog\LogAuditController",
	"audit-timeline" => "controller\syslog\LogAuditTimelineController",
	"log-alt" => "controller\syslog\LogAlertController",
	"log-threaten-detail" => "controller\syslog\LogThreatenDetailController",
	"web-stat" => "controller\syslog\WebStatCliController",
	/*network*/
	"loopback-ipv4"=> 'controller\network\LoopbackIPv4Controller',
	"loopback-ipv6"=> 'controller\network\LoopbackIPv6Controller',
	"listen-interface"=> 'controller\network\ListenIfController',
	"interface-select"=> 'controller\network\SelectIfController',
	"dhcp-service"=> 'controller\network\DhcpServiceController',
	"dhcp-server"=> 'controller\network\DhcpServerController',
	"dhcp-exclusion"=> 'controller\network\DhcpExclusionController',
  	"dhcp-ipbind" => 'controller\network\DhcpIpbindController',
  	"user-recognition" => 'controller\network\UserRecognitionController',
 	"gre-interface" => 'controller\network\GreInterfaceController',
	"interfaces"=> 'controller\network\InterfacePhyController',
	"interfaces-status"=> 'controller\network\InterfaceStatusController',
	"interfaces-trunk"=> 'controller\network\InterfaceTrunkController',
	"interfaces-vlan"=> 'controller\network\InterfaceVlanController',
	"interface-tb"=> 'controller\network\InterfaceTbController',
	"admin-interface"=> 'controller\network\AdminInterfaceController',
	"interface-loopback"=> 'controller\network\LoopbackIfController',
	"interface-floatip"=> 'controller\network\InterfaceFloatIPController',
	"dhcp-monitor"=> 'controller\network\DhcpMonitorController',
	"arp-static"=> 'controller\network\ArpStaticController',
	"arp-dynamic"=> 'controller\network\ArpDynamicController',
	"dns-server"=> 'controller\network\DnsServerController',
	"dns-zone"=> 'controller\network\DnsZoneController',
	"selfip"=> 'controller\network\SelfIpController',
	"route-ipv4"=> 'controller\network\RouteIpv4Controller',
	"route-ipv6"=> 'controller\network\RouteIpv6Controller',
	"tunnel-ipv6"=>'controller\network\NetworkTunnelIpv6Controller',
	"tunnel-ipv6-inf"=>'controller\network\NetworkTunnelIpv6InfController',
	"route-rip"=> 'controller\network\RouteRipController',
	"rip-network"=> 'controller\network\RipNetworkController',
	"rip-interface"=> 'controller\network\RipInterfaceController',
	"route-ospf"=> 'controller\network\RouteOspfController',
	"route-ospfv3" => 'controller\network\RouteOspf3Controller',
	"route-ospfv3-network" => 'controller\network\RouteOspf3NetworkController',
	"route-ospfv3-neighbor" => 'controller\network\RouteOspf3NeighborController',
	"security-zone" => 'controller\network\SecurityZoneController',
	"ospf-network"=> 'controller\network\OspfNetworkController',
	"ospf-interface"=> 'controller\network\OspfInterfaceController',
	"ospf-monitor"=> 'controller\network\OspfMonitorController',
	"ospf-area"=> 'controller\network\OspfAreaController',
	"route-bgp"=> 'controller\network\RouteBgpController',
	"bgp-info"=> 'controller\network\RouteBgpController',
	"bgp-network"=> 'controller\network\BgpNetworkController',
	"bgp-peer"=> 'controller\network\BgpPeerController',
	"route-policy-state"=> 'controller\network\RoutePolicyStateController',
	"route-static"=> 'controller\network\RouteStaticController',
	"route-policy"=> 'controller\network\RoutePolicyController',
	"route6-policy"=> 'controller\network\Route6PolicyController',
	"route-isp"=> 'controller\network\RouteIspController',
	"interface-p2p"=> 'controller\network\InterfaceP2PController',
	"route6-static"=> 'controller\network\RouteStaticIpv6Controller',
	"sslvpn-config"=> 'controller\network\SslvpnConfigController',
	"sslvpn-monitor"=> 'controller\network\SslvpnMonitorController',
	"sslvpn-userbind"=> 'controller\network\SslvpnUserbindController',
	"sslvpn-tunn-if" => 'controller\network\SslvpnTunnIfController',
	"ipsecvpn-tunnel"=> 'controller\network\IpsecvpnTunnelController',
	"ipsec-vpn"=> 'controller\network\IpsecVpnController',
	"ipsec-vpn-v2"=> 'controller\network\IpsecVpnV2Controller',
	"ipsecvpn-sa"=> 'controller\network\IpsecvpnSAController',
	"ipsecvpn-ike-sa"=> 'controller\network\IpsecvpnIKESAController',
	"ipsec-ike"=> 'controller\network\IpsecIKEController',
	"ipsec-easy"=> 'controller\network\IpsecEasyController',
	"local-cert"=> 'controller\network\LocalCertController',
	"overlay"=> 'controller\network\OverlayController',
	"dns-record"=> 'controller\network\DnsRecordController',
	"dns-proxy"=> 'controller\network\DnsProxyController',
	"dns-proxy-rule"=> 'controller\network\DnsProxyRuleController',
	"dns-domain"=> 'controller\network\DnsDomainController',
	"overlay-network"=> 'controller\network\OverlayNetworkController',
	"net-wlan"=> 'controller\network\NetWlanController',
	"net-wlan-detail"=> 'controller\network\NetWlanDetailController',
    "wlan-config"=> 'controller\network\WlanConfigController',
    "net-lte" => 'controller\network\NetLTEController',
    "net-lte-config" => 'controller\network\NetLTECfgController',
    "net-lte-connect" => 'controller\network\NetLTEConController',
    "bridge" => 'controller\network\BridgeController',
    "lte-static" => 'controller\network\LteStaticController',
	"ospf" => 'controller\network\OspfController',
	"flow-mirror" => 'controller\network\FlowMirrorTableController',
	"ddns" => 'controller\network\DDNSController',
	"ddns-update" => 'controller\network\DDNSUpdateController',
	"net-vline-if" => 'controller\network\NetVlineIfController',
	"vpn-user-cfg" => 'controller\network\VPNUsercenterCfgController',
	"vpn-user-oem" => 'controller\network\VPNUsercenterOemController',
	"vpn-subauth-cfg" => 'controller\network\VPNSubauthCfgController',
	"vpn-userkey-manage" => 'controller\network\VPNUserkeyManageController',
	"vpn-user-qrencode-cfg" => 'controller\network\VPNUserQRencodeCfgController',
	"vpn-user-tmlimit-info" => 'controller\network\VPNUserTmlimitInfoController',
	"vpn-ipsecuser" => 'controller\network\VPNIpsecuserController',
	"vpn-client-cfg" => 'controller\network\VPNClientCfgController',
	"upload-client" => 'controller\network\UploadClientController',
	'ndp'=> 'controller\network\NDPController',
	'ndp-bind'=> 'controller\network\NDPBindController',
	"route4-cfg"=> 'controller\network\Route4CfgController',
));

?>
